nodeLinker: node-modules

npmRegistryServer: "https://registry.npmmirror.com"

supportedArchitectures:
  os: [win32]
  cpu: [x64]

enableScripts: true
enableGlobalCache: true

npmScopes:
  sqlite3:
    npmRegistryServer: "https://mapbox-node-binary.s3.amazonaws.com"
    npmAlwaysAuth: false 
  electron:
    npmRegistryServer: "https://registry.npmmirror.com"
    npmAlwaysAuth: false
  "@electron":
    npmRegistryServer: "https://registry.npmmirror.com"
    npmAlwaysAuth: false